#!/usr/bin/env bash

self=$(muchsync --self)
if [ "$self" != 2967698721405478202 ]; then
  echo
  echo "inbox $(notmuch count tag:inbox) email(s)"
  echo "gh $(notmuch count tag:gh-inbox) email(s)"
  exit 0
fi

#### Me
notmuch tag -unread -inbox -- tag:new and from:keegan.csmith@gmail.com
notmuch tag -unread -inbox -- tag:new and from:keegan@sourcegraph.com

#### GitHub
notmuch tag +gh -- tag:new and from:notifications@github.com

#### GitHub flag when people mention me
notmuch tag +flagged +gh/mention -- tag:new and tag:gh and -from:keegan and '(body:keegan or body:keegancsmith)' and -from:sourcegraph-bot
notmuch tag +gh/review -- tag:new and tag:gh and -from:keegan and 'body:"requested your review on"'

#### Gerrit
notmuch tag +gerrit -- tag:new and from:gerritcodereview

#### Mailing lists
notmuch tag +list/notmuch -- tag:new and to:notmuch@notmuchmail.org

#### Likely invoices/receipts to later reference. Manually untag false positives
notmuch tag +invoice -- '(statement or invoice)' to:keegan.csmith@gmail.com

#### Muting threads
notmuch tag -unread -inbox +muted -- tag:new and 'thread:{tag:muted}'

#### Notify bots
notmuch tag -unread -flagged -- tag:new and tag:gh and from:sourcegraph-bot and "codenotify report"
notmuch tag -unread -flagged -- tag:new and tag:gh and 'from:sourcegraph-bot-2' and 'label was applied to the issue'
notmuch tag -unread -flagged -- tag:new and tag:gh and 'from:github-actions[bot]' and 'label was applied to the issue'

#### Low signal
notmuch tag -unread -inbox -- tag:new and tag:gh and 'from:renovate[bot]'
notmuch tag -unread -inbox -- tag:new and tag:gh and 'from:codecov[bot]'
notmuch tag -unread -inbox -- tag:new and 'from:"Linter for Gerrit"'
notmuch tag -unread -inbox -- tag:new and from:no-reply@pganalyze and subject:"critical issues"
notmuch tag -unread -inbox -- tag:new and tag:gh and 'body:(Merged "into master")'
notmuch tag -unread -inbox -- tag:new and tag:gh and 'body:(Merged "into main")'
notmuch tag -unread -inbox -- tag:new and tag:gh and 'body:(Merged "into release")'
notmuch tag -unread -inbox -- tag:new and tag:gh and to:your_activity@noreply.github.com
notmuch tag -unread -inbox -- tag:new and tag:gh and to:push@noreply.github.com

#### Finally put all GitHub notifications in own inbox
notmuch tag -inbox +gh-inbox -- tag:new and tag:gh and tag:inbox

#### Emails to shared inbox I can't unsubscribe to
notmuch tag --remove-all +trash tag:new from:"'npm' via dev" subject:"Successfully published @sourcegraph"
notmuch tag --remove-all +trash tag:new from:nobody@mozilla.org subject:"signed and ready to download"
notmuch tag --remove-all +trash tag:new from:nobody@mozilla.org subject:"Sourcegraph for Firefox" and subject:"updated"
notmuch tag --remove-all +trash tag:new from:admin@sourcegraph.com subject:"Namecheap Renewals"
notmuch tag --remove-all +trash tag:new from:support@buildkite.com subject:"Invoice"
notmuch tag --remove-all +trash tag:new from:dev@sourcegraph.com subject:"Tracking Issue"
notmuch tag --remove-all +trash tag:new from:dev@sourcegraph.com subject:"renovate/docker-sourcegraph-docker-insiders-images"
notmuch tag --remove-all +trash tag:new from:no-reply@zoom.us subject:'has joined your meeting'
notmuch tag --remove-all +trash tag:new to:sourcegraph/deploy-sourcegraph-dogfood-k8s-2

echo
echo "processed $(notmuch count tag:new) email(s)"
echo "inbox $(notmuch count tag:inbox) email(s)"
echo "gh $(notmuch count tag:gh-inbox) email(s)"

notmuch tag -new -- tag:new
