#!/usr/bin/env bash

set -euo pipefail

self=$(muchsync --self)
if [ "$self" != 2967698721405478202 ]; then
	echo "Warning: pre-new hook does nothing on non-gmi machine. Use notmuch-sync instead." >&2
	exit 0
fi

cd ~/.mail/gmail
gmi sync

cd ~/.mail/sourcegraph
test -f ~/VACATION || gmi sync
